<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="11" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="222" started-at="2017-07-27T13:08:29Z" finished-at="2017-07-27T13:08:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="222" started-at="2017-07-27T13:08:29Z" finished-at="2017-07-27T13:08:29Z">
      <class name="com.qainfotech.tap.training.snl.api.BoardTest">
        <test-method status="PASS" signature="NoUserWithSuchUUIDExceptionTest()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="NoUserWithSuchUUIDExceptionTest" duration-ms="32" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <exception class="com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException">
            <message>
              <![CDATA[No Player with uuid '7d2c002f-a3f9-4559-a6f2-e7b8c5433b73' on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException: No Player with uuid '7d2c002f-a3f9-4559-a6f2-e7b8c5433b73' on board
	at com.qainfotech.tap.training.snl.api.Board.deletePlayer(Board.java:115)
	at com.qainfotech.tap.training.snl.api.BoardTest.NoUserWithSuchUUIDExceptionTest(BoardTest.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NoUserWithSuchUUIDExceptionTest -->
        <test-method status="PASS" signature="deletePlayerTest()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="deletePlayerTest" duration-ms="62" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePlayerTest -->
        <test-method status="PASS" signature="registerPlayerTest()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="registerPlayerTest" duration-ms="10" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayerTest -->
        <test-method status="FAIL" signature="registerPlayerTestForGameInProgressException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="registerPlayerTestForGameInProgressException" duration-ms="13" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method BoardTest.registerPlayerTestForGameInProgressException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67] should have thrown an exception of type class com.qainfotech.tap.training.snl.api.GameInProgressException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method BoardTest.registerPlayerTestForGameInProgressException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67] should have thrown an exception of type class com.qainfotech.tap.training.snl.api.GameInProgressException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayerTestForGameInProgressException -->
        <test-method status="PASS" signature="registerPlayerTestForMaxPlayerException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="registerPlayerTestForMaxPlayerException" duration-ms="12" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <exception class="com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption">
            <message>
              <![CDATA[The board already has maximum allowed Player: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption: The board already has maximum allowed Player: 4
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:70)
	at com.qainfotech.tap.training.snl.api.BoardTest.registerPlayerTestForMaxPlayerException(BoardTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayerTestForMaxPlayerException -->
        <test-method status="PASS" signature="registerPlayerTestForPlayerExistException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="registerPlayerTestForPlayerExistException" duration-ms="9" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <exception class="com.qainfotech.tap.training.snl.api.PlayerExistsException">
            <message>
              <![CDATA[Player 'vids' already exists on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.PlayerExistsException: Player 'vids' already exists on board
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:75)
	at com.qainfotech.tap.training.snl.api.BoardTest.registerPlayerTestForPlayerExistException(BoardTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.PlayerExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayerTestForPlayerExistException -->
        <test-method status="PASS" signature="rollDiceForInvalidTurnException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="rollDiceForInvalidTurnException" duration-ms="7" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <exception class="com.qainfotech.tap.training.snl.api.InvalidTurnException">
            <message>
              <![CDATA[Player '0a56e6b3-5295-442f-8ab6-67ad429b0a1b' does not have the turn]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.InvalidTurnException: Player '0a56e6b3-5295-442f-8ab6-67ad429b0a1b' does not have the turn
	at com.qainfotech.tap.training.snl.api.Board.rollDice(Board.java:172)
	at com.qainfotech.tap.training.snl.api.BoardTest.rollDiceForInvalidTurnException(BoardTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.InvalidTurnException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rollDiceForInvalidTurnException -->
        <test-method status="PASS" signature="rollDiceForLadder()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="rollDiceForLadder" duration-ms="15" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rollDiceForLadder -->
        <test-method status="PASS" signature="rollDiceForSnake()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="rollDiceForSnake" duration-ms="7" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rollDiceForSnake -->
        <test-method status="PASS" signature="rollDiceTestForNotChangingThePosition()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="rollDiceTestForNotChangingThePosition" duration-ms="6" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rollDiceTestForNotChangingThePosition -->
        <test-method status="PASS" signature="rollDiceTestForStartingTheGame()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@548b7f67]" name="rollDiceTestForStartingTheGame" duration-ms="9" started-at="2017-07-27T18:38:29Z" finished-at="2017-07-27T18:38:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rollDiceTestForStartingTheGame -->
      </class> <!-- com.qainfotech.tap.training.snl.api.BoardTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
